config.yaml.dist, flathunter.py, flathunter/config.py, main.py, test/test_config.py
This adds the configuration option `database_location` which allows users to configure the location of the database.
The field defaults to the current directory.
=> Make database location configurable

config.yaml.dist
Fixes https://github.com/flathunters/flathunter/issues/27.
=> config.yaml: Update list of supported websites.

config.yaml.dist
fixed wrong API parameter
see https://developers.google.com/maps/documentation/distance-matrix/intro#travel_modes
=> fix wrong API parameter

config.yaml.dist, flathunt.py, flathunter/abstract_crawler.py, flathunter/config.py, flathunter/crawl_ebaykleinanzeigen.py, flathunter/crawl_immobilienscout.py, flathunter/crawl_immowelt.py, flathunter/crawl_wggesucht.py, flathunter/default_processors.py, flathunter/gmaps_duration_processor.py, flathunter/googlecloud_idmaintainer.py, flathunter/hunter.py, flathunter/idmaintainer.py, flathunter/sender_telegram.py, flathunter/web_hunter.py, test/dummy_crawler.py
=> Fix debug log

flathunter/abstract_crawler.py
I added randomization of user-agents so that the user-agent changes before every get request. This will hopefully make the crawler harder to detect for protection mechanisms.
=> Added randomization of user agent in header

config.yaml.dist, flathunter/filter.py
Added a max_price_per_square filter and added it to the config. It's probably more interesting when searching for something to buy.
=> Added max price per square filter

flathunter/crawl_immobilienscout.py
I got a NoneType error last night, in crawling immoscout24. I introduced that error with my last PR, sry. It probably happened because of bad page loading, because of my router reseting. This way the page only partly loaded, which confused the crawler. Couldn't reproduce it though, but this should fix it.
=> Fixed potential NoneType Error

flathunter/abstract_crawler.py, flathunter/crawl_immobilienscout.py, flathunter/crawl_wggesucht.py, flathunter/filter.py, flathunter/web_hunter.py
=> Bugfix for IndexError on WG Gesucht

Pipfile, Pipfile.lock, README.md, config.yaml.dist, flathunter/abstract_crawler.py, flathunter/config.py, flathunter/crawl_ebaykleinanzeigen.py, flathunter/crawl_immobilienscout.py, flathunter/crawl_wggesucht.py, test/test_crawl_immobilienscout.py, test/test_processor.py
I added 2captcha to solve the issue with immobilienscout. To solve that I use Selenium and 2captcha now, it is optional to use it.
=> add 2captcha

flathunter/crawl_immobilienscout.py
=> closes #72 - check if galleryAttachments exists. Default to placeholder link

README.md, flathunter/config.py, flathunter/crawl_immobiliare.py
Related to https://github.com/flathunters/flathunter/pull/63 , I have added Immobiliare.it Crawler.
This does not implement the changes from it though. I thought that maybe merging would be easier, as this PR would be likely be merged before that one, as it has way less changes.
Tell me what do you think!
=> Added Immobiliare crawler

flathunter/config.py, flathunter/crawler_subito.py
Related to https://github.com/flathunters/flathunter/pull/74 and https://github.com/flathunters/flathunter/pull/63 , I have finally added all three of the major Italian rent websites that I know.
In this I have skipped over the documentation as I don't think it would make a lot of sense adding the same thing again :D
Again, tell me what do you think!
=> Added subito crawler

Pipfile, Pipfile.lock, README.md, config.yaml.dist, flathunter/abstract_crawler.py, flathunter/config.py, flathunter/crawl_idealista.py, flathunter/proxies.py
idealista.it is an analogous website for flats and houses alike.
I have implemented the interface for scraping it, although I also needed to go a step further and user random user angents + free proxies, to avoid being captcha-blocked.
Maybe the proxy part and user-agent can still be used?
=> Added Idealista.it, and using proxies

flathunter/abstract_crawler.py, flathunter/config.py, flathunter/crawl_ebaykleinanzeigen.py, flathunter/crawl_immobiliare.py, flathunter/crawl_immobilienscout.py, flathunter/crawl_immowelt.py, flathunter/crawl_wggesucht.py, flathunter/crawler_subito.py, test/test_crawl_ebaykleinanzeigen.py, test/test_crawl_immobilienscout.py, test/test_crawl_immowelt.py, test/test_crawl_wggesucht.py, test/test_hunter.py
Added the Proxy option to all the crawlers if enabled. Maybe some people find this useful..
Also:
* linting
* fix tests
* removed unneeded packages
=> Add Proxy to all crawlers as an option

flathunter/crawl_wggesucht.py
Per feedback from @fkalbe, closes #79
=> Update address fetcher for WG Gesucht

flathunter/crawl_wggesucht.py
Fixes #47 
WG-Gesucht only applies some filters (e.g. limited quarters) after a page reload, even though these filters are encoded in the URL. I think the most straightforward way to implement this was by changing the `get_soup_from_url()` method inherited from `abstract_crawler`.
=> Reload page once on wg-gesucht to correctly apply all filters

flathunter/crawl_ebaykleinanzeigen.py
Fixes #104 by updating the data extraction method to work on the updated Ebay Kleinanzeigen website.
=> Fix data extraction for updated Ebay Kleinanzeigen website

flathunter/crawl_ebaykleinanzeigen.py
=> changed classname for images after ebay-kleinanzeigen update

flathunter/abstract_crawler.py
=> Fix geetest solving

README.md, flathunt.py, flathunter/heartbeat.py
Adding an additional optional argument for CLI where users can set the interval time to receive heartbeat messages to check that their bot is alive.
=> added heartbeat message

Pipfile, flathunter/abstract_crawler.py, flathunter/captcha_solver.py, flathunter/hunter.py
Occasionally, as documented by 2captcha, the service will return
a response with the content of "500 Internal Server Error". It's unclear
if in this case, the HTTP status code is set properly, as that's not
documented anywhere and this case is hard to reproduce, so the error is
handled by looking at the response body, as it is in the other cases.
Logs and stack trace:
```
Solve geetest
Captcha status: CAPCHA_NOT_READY
Captcha promise: 500 Internal Server Error
Traceback (most recent call last):
File "flathunt.py", line 111, in <module>
main()
File "flathunt.py", line 107, in main
launch_flat_hunt(config, heartbeat)
File "flathunt.py", line 55, in launch_flat_hunt
hunter.hunt_flats()
File "/home/flathunter/flathunter/flathunter/hunter.py", line 42, in hunt_flats
for expose in …
```
=> Fix crash when 2catpcha returns a 500 server error

requirements.txt
As mentioned by @jukoson in #161.
=> Add backoff to requirements.txt

Pipfile, Pipfile.lock
=> Fix pipfile

flathunter/abstract_crawler.py
Reverts f5ebc667 from https://github.com/flathunters/flathunter/pull/172
See: https://github.com/flathunters/flathunter/pull/172#issuecomment-1138310071
=> revert f5ebc667

flathunter/crawl_wggesucht.py
There was an issue where ads where between the posts which broke the crawler because it expected some elements inside the html body.
=> Fix problem with ads between the posts

flathunter/captcha/imagetyperz_solver.py, flathunter/config.py
- Renamed file ```imagetypers_solver.py``` to ```imagetyperz_solver.py```
- Renamed class- and variable-names accordingly, as well as mentions in comments and logs
- Renamed configuration option "captcha/imagetypers" to "captcha/imagetyperz"
- Implemented warning for users using old configuration option
=> Fixed ImageTyperz typo (renamed "ImageTypers" to "ImageTyperz")

flathunt.py, flathunter/abstract_crawler.py, flathunter/captcha/imagetyperz_solver.py, flathunter/captcha/twocaptcha_solver.py, flathunter/config.py, flathunter/crawl_ebaykleinanzeigen.py, flathunter/crawl_idealista.py, flathunter/crawl_immobiliare.py, flathunter/crawl_immobilienscout.py, flathunter/crawl_immowelt.py, flathunter/crawl_wggesucht.py, flathunter/crawler_subito.py, flathunter/default_processors.py, flathunter/gmaps_duration_processor.py, flathunter/googlecloud_idmaintainer.py, flathunter/heartbeat.py, flathunter/hunter.py, flathunter/idmaintainer.py, flathunter/logging.py, flathunter/sender_mattermost.py, flathunter/sender_telegram.py, flathunter/web_hunter.py, test/dummy_crawler.py
- Moved logging-related logic to ```flathunter/logging.py```
- Made files use shared logger (being exported from logging file stated above)
- Set log level for "requests" module there just once, removed duplicate calls from other files
- Standardized logs across Crawler implementations
- Changed format for report of entries found by Crawlers
- Translated logs from German to English
- Fixed spelling/typos for logs
- Provided more meaningful context to logs
- Removed some pointless logs altogether
=> Improved logging

.github/dependabot.yml
This PR is intend to keep the dependencies up to date using Dependabot for weekly checks
=> Dependabot integration

flathunter/chrome_wrapper.py, test/test_chrome_wrapper.py
New chrome version handling failed to correctly parse chromium version strings
=> Handle chromium version string

flathunter/abstract_crawler.py, flathunter/config.py, flathunter/crawl_immobilienscout.py, flathunter/exceptions.py, flathunter/sender_telegram.py
Add handling for Telegram API backoff messages
=> Add clearer messaging for the case where the Immoscout bot-detection kicks in

README.md
I setup a new server where I installed flathunter, but it didn't work without installing google chrome
=> add google chrome as prerequisite

flathunt.py, flathunter/config.py
I added a pause period to the hunting loop. This can be used to save some captcha solving during the night time when nobody publishes any new advertisements or checks his mobile.
This can be enabled with loop.pause.from and loop.pause.till in the config.
E.g.:
loop:
pause:
from: "20:00"
till: "08:00"
will pause the loop between 20:00 and 08:00.
If "from" equals "till" (which is the default) then the loop won't be paused.
=> Paused loop for a given time span

flathunt.py, flathunter/time_utils.py, flathunter/utils/time_utils.py, test/test_time_utils.py
As suggested, some clean up done and improved coverage by adding unit tests.
=> Pause period clean up and test

flathunter/exceptions.py, flathunter/sender_telegram.py, test/test_sender_telegram.py
=> Add tests and better handling of stampede protection messages

.pylintrc, Pipfile, Pipfile.lock, README.md, flathunter/abstract_processor.py, flathunter/config.py, flathunter/filter.py, flathunter/gmaps_duration_processor.py, flathunter/heartbeat.py, flathunter/idmaintainer.py, flathunter/processor.py, flathunter/sender_telegram.py, flathunter/utils/list.py, flathunter/web/util.py, flathunter/web/views.py, flathunter/web_hunter.py, test/test_config.py, test/test_googlecloud_idmaintainer.py, test/test_id_maintainer.py
Start some basic type checking
=> Add env-variable support for filters

flathunt.py, flathunter/argument_parser.py, main.py
I just copied the lines from flathunt.py. Without these lines, you cannot specify the config when starting locally.
=> Add possibility to start main.py with config.yml

config.yaml.dist
=> Add example apprise config for signal

flathunter/chrome_wrapper.py
Added a standard macOS Chrome path, added extra Chrome options for macOS users
Code from https://github.com/flathunters/flathunter/issues/508
=> Issue 508 (ChromeNotFound on macOS)

flathunter/abstract_crawler.py, flathunter/crawler/wggesucht.py, test/crawler/test_crawl_wggesucht.py
=> Switch html.parser for lxml in BeautifulSoup invocations

flathunter/crawler/wggesucht.py
Reverts flathunters/flathunter#520
=> Revert "Revert "Fix for wggesucht crawler to only consider the desired listings""

Dockerfile
Fixes #533 
Only changed the Dockerfile.
Local tests all run successfully, and also tested it with some own examples.
Lets see what github actions say.
=> Swap Google Chrome for Chromium in Dockerfile

docker-compose.yaml
=> Increases shm size in docker-compose.yaml to fix WebDriverException

flathunter/heartbeat.py
I set my sleeping_time a lot lower than 600 seconds so I made some changes to the heartbeat class.
=> Calculate heartbeat interval using sleeping_time

test/crawler/test_crawl_vrmimmo.py
=> Disable vrimmo tests until someone asks for them back

config.yaml.dist
Resolves an issue with the parsing of the default config.
=> Fix quoting issue in config dist

README.md, flathunter/config.py, flathunter/crawler/immobilienscout.py, flathunter/crawler/kleinanzeigen.py, flathunter/crawler/vrmimmo.py, flathunter/webdriver_crawler.py, test/test_config_env.py
Make it possible to override the IS24 cookie with an environment variable setting. Add some tests for the override.
=> Add environment override for IS24 cookie

CODE_OF_CONDUCT.de.md, CODE_OF_CONDUCT.en.md
Update templates to the same version.
=> Update code of conduct to include email address

flathunter/crawler/kleinanzeigen.py
Fixes several problems with Kleinanzeigen, including an error with faulty title_el (https://github.com/flathunters/flathunter/issues/515) which crashed the application as well as some not correctly formatted strings like rooms and square meters.
Also changed around the usage of `soup.find()` a bit.
Comments are welcome, I already tested most of these changes in my own repository and everything works so far.
=> Fix: Several problems with Kleinanzeigen

flathunter/crawler/immowelt.py
Immowelt changed the urls and the website format. The old crawler stopped working.
I updated the elements and the methods of `extract_data` to match the new website. It has been tested for my own purposes and it works as expected.
=> Updated crawler for new immowelt website
