config.yaml.dist, flathunter.py, flathunter/crawl_immobilienscout.py, flathunter/crawl_wggesucht.py, flathunter/hunter.py, flathunter/sender_telegram.py
This merge will add:
* add option to exclude flats from being sent via regex
* refactoring
* fixed unreachable log statement
=> Add exclude feature and refactoring

flathunter/crawl_immobilienscout.py
Fixing the problem when user did not specify `pagenumbe` in the immobilienscout URL, making it loop over the same page over and over again. This caused, getting the same flat on Telegram several times. 
Also fixed the `rooms` attribute, which was sending too much content, had to trim it.
Some small refactoring
=> Bugfixing immobilienscout crawler 

flathunter.py, flathunter/hunter.py, test/test_hunter.py
Exclusions code was returning no exposes if no exclusions were configured
Added test for Hunter class
=> Fixed bug in exclusion filtering

config.yaml.dist, flathunter/hunter.py
Commenting / uncommenting instructions around Distance matrix api code were unclear and buggy. Replaced with a flag.
=> Slight clean up around enabling distance API

flathunter/crawl_ebaykleinanzeigen.py
EBay appears to filter some user agents that correspond to scripts. Since the URLs we access don't seem to be excluded by robots.txt, one assumes this is over-zealous DoS attack protection. Use a browser User Agent to avoid the filter.
=> Add reference user agent for ebay crawler

Pipfile, Pipfile.lock, flathunter.py, flathunter/abstract_processor.py, flathunter/config.py, flathunter/default_processors.py, flathunter/filter.py, flathunter/gmaps_duration_processor.py, flathunter/hunter.py, flathunter/processor.py, flathunter/sender_telegram.py, main.py, test/dummy_crawler.py, test/test_gmaps_duration_processor.py, test/test_hunter.py, test/test_id_maintainer.py, test/test_processor.py, test/test_web_interface.py
In preparation for a more diverse feature-set, I've refactored the code so that exposes are passed through a number of filtering / transformation steps. These steps can be joined into a pipeline, which is applied to the results of a crawl to give the processed exposes.
=> Add processing pipelines

flathunter/abstract_crawler.py, flathunter/crawl_ebaykleinanzeigen.py, flathunter/crawl_immobilienscout.py, flathunter/crawl_immowelt.py, flathunter/crawl_wggesucht.py, flathunter/default_processors.py, flathunter/googlecloud_idmaintainer.py, flathunter/idmaintainer.py, flathunter/processor.py, flathunter/web/templates/exposes.html, flathunter/web_hunter.py, test/test_crawl_ebaykleinanzeigen.py, test/test_crawl_immobilienscout.py, test/test_crawl_immowelt.py, test/test_crawl_wggesucht.py, test/test_googlecloud_idmaintainer.py, test/test_id_maintainer.py
Improve the IDMaintainer not to fetch all records - performance was starting to suffer on a database with 1000s of exposes.
Add code to fetch the 'available from' dates for flats, by crawling the exposé pages.
=> Improve efficiency of IDMaintainer, extract 'from' dates

flathunter/crawl_immobilienscout.py, flathunter/crawl_immowelt.py, flathunter/web/templates/about.html, flathunter/web/templates/exposes.html, flathunter/web/templates/index.html, flathunter/web/templates/layout.html, flathunter/web/templates/resources.html, flathunter/web/views.py, flathunter/web_hunter.py, test/test_web_interface.py
Added page with information about rights for tenants
Fixed bug with exposes only being sent through one user filter
Fixed date bug in exposes for 'sofort' rentals
Don't send referrer when users click on expose links
Make it clear that the 'flathunter' website is currently setup for Berlin only
=> Bug fixes, Renter info page

flathunter/crawl_immobilienscout.py
Now, entries without price, size, or room count are more explicitly skipped.
=> Fix a bug where an entry without a price caused a crash.

flathunter/crawl_immobilienscout.py
Just leave all the ambiguous attributes empty.
This is a bit quick and dirty; I'm open to better options.
=> Don't skip entries with missing attributes.

flathunter/crawl_wggesucht.py
Flats with fewer than 10 m^2 were failing
=> Fix wggesucht for small flats

flathunter/crawl_ebaykleinanzeigen.py
When data is missing, a NoneType exception might be triggered. Fixes #34
=> Catch more exceptions

README.md, config.yaml.dist
The google cloud documentation is super helpful for beginners!
This hopefully makes it even better. E.g. I think https://github.com/flathunters/flathunter/issues/30 might have been avoided with this config.yaml change.
paired with @jmjr
=> small google cloud documentation cleanups

flathunter/crawl_immobilienscout.py
Before the yellow part was included in the search. Those are sponsored results, that often don't fit the search criteria.
=> Fixed immoscout24 crawler also crawling in the "Weitere Angebote..." section

flathunter/abstract_crawler.py
the get_entries_from_javascript() expected to get a result from the driver's get method, but fails since it got called only when Captcha was present. This is not the case all the time, specially at the start, therefore ran into the JavascriptException.
=> fix empty json response when no captcha

Dockerfile
Thanks for the awesome project. I recently adjusted the Dockerfile to make it run chrome web driver which is necessary for the 2captcha service.
I would like to contribute it if you want. It could also be renamed to keep the original version which is still working if chrome web driver is not necessary.
=> Adjust Dockerfile to use chromedriver for captchas

flathunter/abstract_crawler.py
Seems like Immoscout doesn't implement the captcha via iframe anymore. So i propose to use the data-sitekey instead.
=> Use data-sitekey for recaptcha

requirements.txt
pkg-resources==0.0.0 in requirements.txt breaks the install of the dependencies (pip3 install -r requirements.txt). It seems, the dependency is added when freezing the requirements on Ubuntu https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1635463.
=> Remove pkg-resources==0.0.0

flathunter/crawl_wggesucht.py, flathunter/string_utils.py, test/test_string_utils.py
This will ensure a single slash in the constructed url regardless of
whether the href attribute contains a leading slash or not.
=> Avoid accidentally generating a URL with a double slash after the domain

flathunter/crawl_immowelt.py
When setting logging to debug, outputting the number of extracted entries fails, as it passed the raw entries, not `len(entries)`as in the other crawlers, and thus doesn't fit with `%d`.
=> Fixed debug output on immowelt crawler

flathunter/filter.py
Currently all filtered tags will be compared to the lowercase title. This implies, that a match is only possible if filtered tags are written all lowercase.
Instead, this PR compares the filtered tags to the original title but case-insensitve. No need to convert title to lowercase, nor to restrict the user to only enter lower-case filtered tags
=> Make title match case insensitive

flathunter/abstract_crawler.py
This should hopefully curb the problem of ever-expanding web-driver instances. I haven't had time to test this yet, but wanted to open this PR so others could test it if they like.
=> WIP/Untested: add driver.close() to close driver and prevent accumulation

Pipfile, Pipfile.lock, README.md, config.yaml.dist, flathunt.py, flathunter/abstract_crawler.py, flathunter/config.py, flathunter/crawl_immobilienscout.py, flathunter/logging.py
**This update aims to reduce installation complexity by rendering a manual ChromeDriver install obsolete.** [WebDriverManager](https://pypi.org/project/webdriver-manager/) ("WDM") automatically takes care of the driver's installation in the background. By default it does not produce any output, *unless verbose mode is active*.
**Changes:**
- Added ```webdriver-manager``` package
- Implemented WDM as service instead of static driver path for ChromeDriver launch
- This also removes a "deprecated" warning issued by Selenium's WebDriver module ["DeprecationWarning: executable_path has been deprecated, please pass in a Service object"](https://github.com/flathunters/flathunter/blob/a73b6cfd23e36ca3dceca62096af7edfac7a3603/flathunter/abstract_crawler.py#L56)
- Removed ChromeDriver install …
=> Automate ChromeDriver install by using WebDriverManager

.dockerignore, Dockerfile, README.md
There have been [issues](https://github.com/flathunters/flathunter/issues/121) around Flathunter's Docker setup, which also now had stopped working entirely since ```requirements.txt``` was removed from the repository.
- **Changed Dockerfile base from ```joyzoursky/python-chromedriver``` to plain ```python```.** Now that WebDriverManager is used to automatically setup ChromeDriver, it is also no longer necessary to build off joyzoursky's ```python-chromedriver``` image. 
- **Added Google Chrome install to Dockerfile.** This is required for WebDriverManager's ChromeDriver setup to work and had been taken care of before by basing the Dockerfile off the ```python-chromedriver``` image.
- **Allowed for Dockerfile to install dependencies without ```requirements.txt```.** Building the image …
=> Docker-related updates

flathunter/crawl_wggesucht.py
wg-gesucht is commonly used also for short-term rent. 
If a user is searching short term rent the period is really important, and with this modification, it would appear in the notification. 
Even if a user is searching only for Long term renting, wg-gesucht does not allow filtering with the move-out date so having this information would allow discarding a rent quickly just by looking at the notification.
If there is a move-out date the title would become:
```
if len(dates) == 2:
title = f"{title} vom {dates[0]} bis {dates[1]}"
else:
title = f"{title} ab dem {dates[0]}"
```
An alternative solution would be to expose the `from` and `to` placeholders in the message configuration.
=> Add date 'to' in the title of wg-gesucht

Pipfile, Pipfile.lock, README.md, config.yaml.dist, flathunt.py, flathunter/heartbeat.py, flathunter/processor.py, flathunter/sender_apprise.py, test/test_sender_apprise.py
[Apprise](https://github.com/caronc/apprise) is a very famous and supported python library to send notifications via easy-to-configure "URLs". 
Including Apprise in Flathunter would allow users to send notifications using almost every service they want.
For example, I would like to receive notifications on my [Gotify](https://github.com/gotify/server) server and if Flathunter would use Apprise then I would be able to receive notifications there. Other users may want to use other services, and using Apprise there would not be the need to support these services one by one.
One point of discussion is that Apprise supports Telegram and Mattermost, I did not touch the two senders but it would be possible to replace the current logic to use Apprise, for example, one could build the Apprise URL …
=> Allow notification via Apprise

.gitignore, Dockerfile, Dockerfile.gcloud.job, Pipfile, Pipfile.lock, README.md, chrome_driver_install.py, cloud_job.py, cloudbuild.yaml, flathunt.py, flathunter/config.py, flathunter/crawl_immobilienscout.py, flathunter/googlecloud_idmaintainer.py, flathunter/heartbeat.py, flathunter/hunter.py, flathunter/logging.py, flathunter/processor.py, flathunter/sender_mattermost.py, flathunter/sender_telegram.py, main.py, test/test_config.py, test/test_web_interface.py
This PR adds support for Google-Cloud-Run, and adds a docker image that can be launched to trigger a one-time crawl (which can then be setup to run on a schedule).
I have refactored the config handling so that it's possible to pass the relevant config by environment variables.
This needs a bunch of documentation still - opening the PR for discussion
=> Dockerfile and script for running crawl jobs in Google Cloud Run with captcha support

Pipfile, Pipfile.lock, flathunter/abstract_crawler.py
This PR solves #210.
Changes: Added [undetected-chromedriver](https://github.com/ultrafunkamsterdam/undetected-chromedriver) to remove selenium's fingerprints, which allows us to crawl `immobilienscout24` with less pain.
Note: The website may still randomly block requests with captchas, so we can't eliminate captcha solvers. If chrome runs without `--headless` flag, most likely the site will not show any captchas.
=> Stealthy selenium - Remove selenium's fingerprints

.github/workflows/tests.yml, .gitignore, flathunter/config.py, flathunter/hunter.py, test/test_config.py, test/test_crawl_ebaykleinanzeigen.py, test/test_crawl_immobilienscout.py, test/test_crawl_immowelt.py, test/test_crawl_wggesucht.py, test/test_gmaps_duration_processor.py, test/test_googlecloud_idmaintainer.py, test/test_hunter.py, test/test_id_maintainer.py, test/test_processor.py, test/test_sender_mattermost.py, test/test_sender_telegram.py, test/test_statistics_view.py, test/test_web_interface.py, test/utils/config.py
The github runner (and local test runs) fails because the test suite does not support captcha solving - test_crawl_immobilienscout.py always fails.
I've refactored the environment handling and the test suite so that the test suite can be run passing FLATHUNTER_2CATPCHA_API_KEY in the environment. With this set, the tests pass in the runner (and probably for users)
After merge, the environment secrets will have to be added to the flathunter repo - we can use my 2captcha key
=> Add support for running test suite with captcha solving

Dockerfile
This has the effect that all image layers that are created by commands up until `COPY . .` on line 8 are cached. This significantly shortens the docker image's build time when only files other than the Pipfiles are changed.
=> Separate commands for dependency installation in Dockerfile

config.yaml.dist, flathunter/crawl_immobilienscout.py
This PR let's user to set GET request header cookie enabling with enables them to surpasss the bot detection script by immoscout24 #302. The cookie should be copied from a logged in session of a user. Once the cookie is compromised a new one should be created.
=> set GET request header cookie

cloud_job.py
Fixes #373, `flathunter_config` just doesn't exist. `config` does.
=> Fix config namespace for the cloud job (fixes #373)

flathunter/config.py
makes it easier to use float values for pps (like 19.5)
=> use float instead of int for price per sqm

flathunter/abstract_crawler.py
I found an API request in the project that doesn't really do anything except printing a warning. In case of a driver present, all of the subsequent page evaluation and captcha solving is done without the need for this request. To minimize the API requests considering bot detection I moved it so that it will only be executed when no driver is present (i.e. when the function didn't escape already).
=> Improved bot detection by avoiding API request

README.md
Update installation instructions to prevent this permission error:
```bash
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/home/flathunter'
Check the permissions.
```
because `useradd flathunter` does not create a `/home/flathunter` folder without the `-m` flag
=> Update installation guide: create /home for user flathunter

flathunter/config.py, flathunter/crawler/ebaykleinanzeigen.py, flathunter/crawler/idealista.py, flathunter/crawler/immobiliare.py, flathunter/crawler/immobilienscout.py, flathunter/crawler/immowelt.py, flathunter/crawler/meinestadt.py, flathunter/crawler/subito.py, flathunter/crawler/wggesucht.py, test/test_crawl_ebaykleinanzeigen.py, test/test_crawl_immobiliare.py, test/test_crawl_immobilienscout.py, test/test_crawl_immowelt.py, test/test_crawl_meinestadt.py, test/test_crawl_wggesucht.py, test/test_hunter.py
This PR is just for the class namings because we do not need the Prefix in any way.
Also all crawlers are now inside a 'crawler' folder.
=> :recycle: rename Crawler

flathunter/chrome_wrapper.py, test/test_chrome_wrapper.py
We can use the `reg` util to access the registry on Windows -- this enables us to find the installed version of Google Chrome, as Chrome does not respond to --version on Windows.
=> fix #465: determine Chrome version on Windows

config.yaml.dist, flathunter/config.py, flathunter/crawler/vrmimmo.py, test/test_crawl_vrmimmo.py
I have just implemented the crawler for https://vrm-immo.de for my own purposes. 
Maybe it can help someone else.
=> Add VrmImmo Crawler

flathunter/chrome_wrapper.py, flathunter/crawler/kleinanzeigen.py
Hey hey,
quick and dörti hack to use chromedriver. Sry it's dirty, but I am a bit short on time lately.
Anyho, had to patch the chrome options to make it work, besides that just copy pasted the stuff from immoscout as discussed in #510.
Tested it on my side with python3.11 seems to work I guess?
If you want changes / move something from a to b to make it cleaner let me know.
LG
=> Use chromedriver for kleinanzeigen

flathunter/chrome_wrapper.py
This simple change changes the ChromeDriver's user agent from the default to a recent one. Apparently this is all I needed to change to pass the bot detection at Immoscout24. Captcha solving is still needed of course.
=> Force modern user agent in Chrome driver to pass Immoscout bot detection in headless mode

flathunter/crawler/immobilienscout.py
This pull request fixes two minor issues I've encountered in the log while scraping Immoscout24 results.
777ad0c7a2743d51597a3414ad91cda699683e50: Some images on scraped listings are rejected by Telegram for being Webp files, as they fall through the filter that shortens them to just the `.jpg` link. Those are the images used to link to virtual viewings and are apparently just [basic placeholders](
). They're recognisable by the `@xsi.type` property being set to `common:VirtualTour` so it's easiest just to exclude everything but `common:Picture` altogether.
c1c6c4fc9fc81c0548989c236c21eb85562bd366: In some cases, the same filter shortened image links to just a few characters, which failed to be submitted to Telegram as a result. I found this is due to some images on Immoscout carrying the …
=> Fix minor issues with Immoscout24 image extraction

flathunter/crawler/wggesucht.py
I've started my flathunting journey today and noticed that on wg-gesucht.de some (very old) listings were presented to me various times even though they were not even included in what I was searching for. Turns out wg-gesucht includes additional results in a div they label "premium_user_extra_list". 
Those additional results are currently not filtered out because only the elements themselves are checked for the correct id of "liste-", which wouldn't be a big deal if they are included once in the beginning and then blocked on subsequent refreshs thanks to the to id_maintainer. But unfortunately the additional listings are somewhat random on each page refresh, presenting you at times with listings that are months old.
This PR changes the filter to only consider the desired search results by …
=> Fix for wggesucht crawler to only consider the desired listings

flathunter/crawler/wggesucht.py
Reverts flathunters/flathunter#516
=> Revert "Fix for wggesucht crawler to only consider the desired listings"

flathunter/chrome_wrapper.py
According to the [Selenium Dev blog](https://www.selenium.dev/blog/2023/headless-is-going-away/) the headless argument to start a headless chromium instance changed.
To be precise it changed from:
`chrome_options.add_argument("--headless")`
to
`chrome_options.add_argument("--headless=new")`
At the same time i also removed the workaround at line 67-69:
```
setattr(chrome_options, "headless", True)
```
`setattr` is setting the headless attribute directly as a child element to chrome_options, in contrast to `chrome_options.add_argument` adding the headless attribute to the list attribute "arguments". (See picture)
Therefore i am afraid that the `setattr` is at best useless and at worst it cancels the headless=new again.
=> Update to new selenium chrome headless argument

flathunter/chrome_wrapper.py, test/test_chrome_wrapper.py
Under Fedora the chromium browser binary is named 'chromium-browser'.
This binary name is missing in the chrome-wrapper.py, therefore it is throwing an ChromeNotFound Exception.
This PR simply adds this name to the list of strings the wrapper executes to find the chromium browser.
=> Add Fedora Chromium binary name to chrome_wrapper

flathunter/chrome_wrapper.py, test/test_chrome_wrapper.py
Something like [#526](https://github.com/flathunters/flathunter/pull/526) should not happen again with this PR.
The empty returns are now calculated dynamically by counting the amount of linux binary names in the CHROME_BINARY_NAMES list and prepending/appending it to the "mock return list".
Also some comments about the functionality of this test and why there are  some empty return values for the next contributor.
For this PR to work i had to make the CHROME_BINARY_NAMES list used in the get_chrome_version function globally accessible.
=> Optimize chrome wrapper test and describe functionality

flathunter/crawler/immobilienscout.py
All crawlers report the number of found entries in the debug log, but Immoscout does not when the Selenium web driver is enabled. This makes it a bit inconsistent as it can look like the crawler failed or found no results even when it does, so I made a quick fix to add a debug message.
=> Immoscout crawler: Log number of found entries when using web driver

config.yaml.dist, flathunter/config.py, flathunter/notifiers/sender_apprise.py
This is an addition to #563.
I somehow missed that the attachment limit imposed by the apprise-api service [can be configured](https://github.com/caronc/apprise-api/blob/d1c5d64b2eccbda43ce5b878f9d8b2c3b4a3488b/apprise_api/core/settings/__init__.py#L208) so IMO there shouldn't be a fixed limit of attachments sent by flathunter.
Sorry for not thoroughly checking before opening the other PR.
=> Add option to limit number of images sent via Apprise

flathunter/argument_parser.py
Changes in the Env variable processing require the variable to be accessed by calling it as a function. Fixes #588
=> Resolve value before comparing to None

flathunter/crawler/immowelt.py
ImmoWelt shows room numbers as ```[COUNT] Zi.``` (e.g. ```3 Zi.```). 
This has not been taken into account before, which leads to displays like this:
flathunter.codders.de:
Telegram:
=> fix: Removed " Zi." from ImmoWelt rooms text parsing

README.md
See https://docs.docker.com/compose/install/linux/
=> No longer reference deprecated docker-compose command.

flathunter/captcha/capmonster_solver.py
Noticed that the error json key has a typo while I got this json response from capmonster in headless mode (possibly another bug as it is always working with headed chrome):
`{'errorId': 1, 'errorCode': 'ERROR_CAPTCHA_UNSOLVABLE', 'errorDescription': 'This type of captchas is not supported by the service or the image does not contain an answer, perhaps it is too noisy. It could also mean that the image is corrupted or was incorrectly rendered. '}`
=> fix capmonster json key

flathunter/crawler/wggesucht.py
WG-Gesucht error ("No title found - skipping") - h3 was changed to h2
=> Change h3 to h2 on WG-Gesucht crawler

README.md, config.yaml.dist, flathunt.py, flathunter/config.py, flathunter/time_utils.py
This PR allows for adding a random delay of up to ten percent to `loop.sleeping_time`. This will (hopefully) improve bot detection evasion by making Flathunter behave non-deterministically.
Introduces a helper function `_to_bool` to convert truthy/falsy config parameters to booleans. This could be applied to ENV variables like `FLATHUNTER_VERBOSE_LOG` as well.
=> Feature: Random sleep interval jitter
